# Generated by Django 4.2.3 on 2024-06-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="admin_dark_mode",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="admin_dark_mode",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
