# Generated by Django 4.2.3 on 2024-02-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_historicalrole_historicaluser_role_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRole',
        ),
    ]
