# Generated by Django 4.2.3 on 2024-02-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
        ('users', '0004_delete_historicalrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financials.account'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='financials.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
