repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      language: python
      types_or: [python, pyi]
      entry: ruff check
    - id: formatting
      name: Format Code
      language: python
      types_or: [python, pyi]
      entry: ruff format --check
    - id: run-tests
      name: Run Unit Tests
      language: system
      entry: python manage.py test
      pass_filenames: false
      stages: [pre-push]
