repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      language: python
      types_or: [python, pyi]
      entry: ruff check
    - id: formatting
      name: Format Code
      language: python
      types_or: [python, pyi]
      entry: ruff format --check
