services:
  web:
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  staticfiles:
