version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=usuario1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=db1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
