# Generated by Django 4.2.3 on 2024-03-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Print",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.PositiveSmallIntegerField()),
                ("minutes", models.PositiveSmallIntegerField()),
                ("grams", models.PositiveSmallIntegerField()),
                (
                    "layer_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.2, max_digits=2
                    ),
                ),
                ("infill", models.PositiveSmallIntegerField(blank=True, default=20)),
                (
                    "nozzle",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0.4, max_digits=2
                    ),
                ),
                ("speed", models.PositiveSmallIntegerField(blank=True, default=40)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "g_code",
                    models.FileField(blank=True, null=True, upload_to="print_gcode/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("x_scale", models.PositiveSmallIntegerField()),
                ("y_scale", models.PositiveSmallIntegerField()),
                ("z_scale", models.PositiveSmallIntegerField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="print_model/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintModelRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(blank=True, default=1)),
                (
                    "print",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="prints.print"
                    ),
                ),
                (
                    "print_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prints.printmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintMaterialColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, default="white", max_length=50)),
                ("remaining", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prints.printmaterial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="print",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prints.printmaterial"
            ),
        ),
        migrations.AddField(
            model_name="print",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddConstraint(
            model_name="printmodelrelation",
            constraint=models.UniqueConstraint(
                fields=("print_model", "print"), name="unique_print_model_print"
            ),
        ),
        migrations.AddConstraint(
            model_name="printmaterialcolor",
            constraint=models.UniqueConstraint(
                fields=("material", "color"), name="unique_material_color"
            ),
        ),
    ]
