# Generated by Django 4.2.3 on 2023-07-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField()),
                ('minutes', models.PositiveSmallIntegerField()),
                ('grams', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('x_scale', models.PositiveSmallIntegerField()),
                ('y_scale', models.PositiveSmallIntegerField()),
                ('z_scale', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.print')),
                ('print_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.printmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='print_model/')),
                ('print_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.printmodel')),
            ],
        ),
    ]
