# Generated by Django 4.2.3 on 2024-02-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintMaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='white', max_length=50, unique=True)),
                ('remaining', models.PositiveIntegerField(blank=True, default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.printmaterial')),
            ],
        ),
    ]
