# Generated by Django 4.2.3 on 2024-03-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='infill',
            field=models.PositiveSmallIntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='print',
            name='layer_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, max_digits=2),
        ),
        migrations.AddField(
            model_name='print',
            name='nozzle',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.4, max_digits=2),
        ),
        migrations.AddField(
            model_name='print',
            name='speed',
            field=models.PositiveSmallIntegerField(blank=True, default=40),
        ),
    ]
