# Generated by Django 6.0.2 on 2026-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printmaterial",
            name="slicer_filament",
            field=models.CharField(
                choices=[
                    ("ABS", "ABS"),
                    ("ASA", "ASA"),
                    ("PETG", "PETG"),
                    ("PLA", "PLA"),
                    ("TPU", "TPU"),
                ],
                default="PLA",
                help_text="Tipo de filamento reconocido por Cura en el servicio de estimación.",
                max_length=8,
            ),
        ),
    ]
