# Generated by Django 4.2.3 on 2024-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_printmaterialcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printmaterialcolor',
            name='color',
            field=models.CharField(blank=True, default='white', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='printmaterialcolor',
            constraint=models.UniqueConstraint(fields=('material', 'color'), name='unique_material_color'),
        ),
    ]
