# Generated by Django 4.2.3 on 2024-02-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
