# Generated by Django 6.0.2 on 2026-02-19 18:07

from decimal import Decimal

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def convert_to_singleton(apps, schema_editor):
    PrintRate = apps.get_model("printrates", "PrintRate")
    HistoricalPrintRate = apps.get_model("printrates", "HistoricalPrintRate")
    latest = PrintRate.objects.order_by("-created_at").first()
    rate = latest.rate if latest else Decimal("0.00")
    PrintRate.objects.all().delete()
    created = PrintRate.objects.create(id=1, rate=rate)
    HistoricalPrintRate.objects.create(
        id=created.id,
        rate=created.rate,
        created_at=created.created_at,
        history_date=timezone.now(),
        history_type="+",
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("printrates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPrintRate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical print rate",
                "verbose_name_plural": "historical print rates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(convert_to_singleton, noop_reverse),
    ]
