# Generated by Django 4.2.3 on 2024-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0002_monthlycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
