# Generated by Django 4.2.3 on 2024-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0003_monthlycost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
