# Generated by Django 4.2.3 on 2024-02-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0004_alter_monthlycost_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRateVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minutes_spent_per_print', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
