# Generated by Django 6.0.2 on 2026-05-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printrates", "0004_margin_on_sales_semantics"),
    ]

    operations = [
        migrations.AddField(
            model_name="printratevariables",
            name="default_machine",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID de máquina Cura devuelto por GET /machines del servicio slicer",
                max_length=255,
            ),
        ),
    ]
