# Generated by Django 4.2.3 on 2024-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0005_printratevariables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='printratevariables',
            name='extra_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='printratevariables',
            name='failure_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='printratevariables',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='printratevariables',
            name='minutes_spent_per_print',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
