# Generated by Django 4.2.3 on 2024-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0006_alter_printrate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printratevariables',
            name='failure_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printratevariables',
            name='minutes_spent_per_print',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
