# Generated by Django 4.2.3 on 2024-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0007_alter_printratevariables_failure_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printratevariables',
            name='extra_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
