# Generated by Django 4.2.3 on 2024-02-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0008_alter_printratevariables_extra_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='printratevariables',
            name='available_machine',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
