# Generated by Django 4.2.3 on 2024-02-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0009_printratevariables_available_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printratevariables',
            old_name='available_machine',
            new_name='available_machines',
        ),
    ]
