# Generated by Django 4.2.3 on 2024-02-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printrates', '0010_rename_available_machine_printratevariables_available_machines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printratevariables',
            old_name='available_machines',
            new_name='available_printers',
        ),
    ]
