# Generated by Django 4.2.3 on 2024-02-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('prints', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('delivered', 'Entregada'), ('canceled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('delivered', 'Entregada'), ('canceled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PrintOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('delivered', 'Entregada'), ('canceled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=50)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_order_items', to='prints.printmaterialcolor')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_order_items', to='orders.orderitem')),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_order_items', to='prints.print')),
            ],
        ),
    ]
