# Generated by Django 4.2.3 on 2024-02-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_printmaterialcolor'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='PrintOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='pending', max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_order_items', to='prints.printmaterialcolor')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_order_items', to='orders.orderitem')),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_order_items', to='prints.print')),
            ],
        ),
    ]
