# Generated by Django 4.2.3 on 2024-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_state_printorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('delivered', 'Entregada'), ('canceled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('delivered', 'Entregada'), ('canceled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='printorderitem',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('delivered', 'Entregada'), ('canceled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=50),
        ),
    ]
