# Generated by Django 4.2.3 on 2024-02-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_alter_printmaterialcolor_color_and_more'),
        ('orders', '0003_order_state_alter_orderitem_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_order_items', to='prints.printmaterialcolor'),
        ),
    ]
