# Generated by Django 4.2.3 on 2024-02-29 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_extraproductcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraproductcost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='products.product'),
        ),
    ]
